<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://www.ventanillaunica.gob.mx/privados/ferros/service/consultarestadoguias"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:oxml="http://www.ventanillaunica.gob.mx/privados/ferros/oxml/consultarestadoguias"
	name="ConsultarEstadoGuiasService" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	targetNamespace="http://www.ventanillaunica.gob.mx/privados/ferros/service/consultarestadoguias">
	<wsp:Policy wsu:Id="BasicHttpBinding_IReceptorService_policy">
		<wsp:ExactlyOne>
			<wsp:All>
				<sp:TransportBinding
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:TransportToken>
							<wsp:Policy>
								<sp:HttpsToken RequireClientCertificate="false" />
							</wsp:Policy>
						</sp:TransportToken>
						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>
						<sp:Layout>
							<wsp:Policy>
								<sp:Lax />
							</wsp:Policy>
						</sp:Layout>
						<sp:IncludeTimestamp />
					</wsp:Policy>
				</sp:TransportBinding>
				<sp:SignedSupportingTokens
					xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:UsernameToken
							sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
							<wsp:Policy>
								<sp:WssUsernameToken10 />
							</wsp:Policy>
						</sp:UsernameToken>
					</wsp:Policy>
				</sp:SignedSupportingTokens>
				<sp:Wss10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
						<sp:MustSupportRefIssuerSerial />
					</wsp:Policy>
				</sp:Wss10>
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
	<wsdl:types>
		<xsd:schema
			targetNamespace="http://www.ventanillaunica.gob.mx/privados/ferros/service/consultarestadoguias/imports">
			<xsd:import
				namespace="http://www.ventanillaunica.gob.mx/privados/ferros/oxml/consultarestadoguias"
				schemaLocation="./ConsultarEstadoGuiasService.xsd" />
		</xsd:schema>
	</wsdl:types>


	<wsdl:message name="ConsultarEstadoGuiasPeticion">
		<wsdl:part element="oxml:consultarEstadoGuiasPeticion" name="peticion" />
	</wsdl:message>
	<wsdl:message name="ConsultarEstadoGuiasRespuesta">
		<wsdl:part element="oxml:consultarEstadoGuiasRespuesta" name="respuesta" />
	</wsdl:message>

	<wsdl:portType name="ConsultarEstadoGuiasServicePortType">
		<wsdl:operation name="consultarEstadoGuias">
			<wsdl:input message="tns:ConsultarEstadoGuiasPeticion" />
			<wsdl:output message="tns:ConsultarEstadoGuiasRespuesta" />
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="ConsultarEstadoGuiasServiceWSEndPoint"
		type="tns:ConsultarEstadoGuiasServicePortType">
		<wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
			URI="#BasicHttpBinding_IReceptorService_policy" />
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="consultarEstadoGuias">
			<soap:operation
				soapAction="http://www.ventanillaunica.gob.mx/ventanilla/ConsultarEstadoGuiasService/consultarEstadoGuias" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="ConsultarEstadoGuiasService">
		<wsdl:port binding="tns:ConsultarEstadoGuiasServiceWSEndPoint"
			name="ConsultarEstadoGuiasServiceWSEndPoint">
			<soap:address
				location="http://www.ventanillaunica.gob.mx/ventanilla/ConsultarEstadoGuiasService" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
